import {
  User,
  Device,
  ContentItem,
  Season,
  Episode,
  Collection,
  WatchHistoryItem,
  NodeHealthStatus,
  PlaybackSession,
} from '../../../src/types';

// Pre-seeded high quality content items (Movies & Series with posters & backdrops)
export const initialContent: ContentItem[] = [
  {
    id: 'c101-dune-2',
    tmdb_id: 693134,
    type: 'movie',
    title: 'Дюна: Часть вторая',
    original_title: 'Dune: Part Two',
    release_year: 2024,
    age_rating: '16+',
    rating_imdb: 8.6,
    rating_tmdb: 8.5,
    runtime_minutes: 166,
    overview: 'Пол Атрейдес объединяется с Чани и фременами, возглавляя месть против заговорщиков, уничтоживших его семью. Стоя перед выбором между любовью всей своей жизни и судьбой известной Вселенной, он пытается предотвратить ужасное будущее, которое только он может предвидеть.',
    poster_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 14250,
    genres: ['Фантастика', 'Приключения', 'Драма'],
    country: 'США / Канада',
    director: 'Дени Вильнёв',
    cast: ['Тимоти Шаламе', 'Зендея', 'Ребекка Фергюсон', 'Хавьер Бардем']
  },
  {
    id: 'c102-interstellar',
    tmdb_id: 157336,
    type: 'movie',
    title: 'Интерстеллар',
    original_title: 'Interstellar',
    release_year: 2014,
    age_rating: '12+',
    rating_imdb: 8.7,
    rating_tmdb: 8.4,
    runtime_minutes: 169,
    overview: 'Засуха, пылевые бури и вымирание растений приводят человечество к продовольственному кризису. Коллектив исследователей и учёных отправляется сквозь червоточину в путешествие, чтобы превзойти прежние ограничения человеческих космических путешествий и найти планету с подходящими для человека условиями.',
    poster_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 28900,
    genres: ['Фантастика', 'Драма', 'Приключения'],
    country: 'США / Великобритания',
    director: 'Кристофер Нолан',
    cast: ['Мэттью Макконахи', 'Энн Хэтэуэй', 'Джессика Честейн', 'Майкл Кейн']
  },
  {
    id: 'c103-cyberpunk-edgerunners',
    tmdb_id: 105248,
    type: 'series',
    title: 'Киберпанк: Бегущие по краю',
    original_title: 'Cyberpunk: Edgerunners',
    release_year: 2022,
    age_rating: '18+',
    rating_imdb: 8.3,
    rating_tmdb: 8.6,
    runtime_minutes: 24,
    overview: 'История уличного подростка, пытающегося выжить в городе будущего, одержимом технологиями и модификациями тела. Потеряв всё, он решает стать наемником — киберпалком.',
    poster_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 18400,
    genres: ['Аниме', 'Киберпанк', 'Боевик'],
    country: 'Япония / Польша',
    director: 'Хироюки Имаиси',
    cast: ['КЭНН', 'Аои Юки', 'Хироку Юки']
  },
  {
    id: 'c104-oppenheimer',
    tmdb_id: 872585,
    type: 'movie',
    title: 'Оппенгеймер',
    original_title: 'Oppenheimer',
    release_year: 2023,
    age_rating: '18+',
    rating_imdb: 8.9,
    rating_tmdb: 8.1,
    runtime_minutes: 180,
    overview: 'История жизни американского физика Роберта Оппенгеймера, который стоял во главе Манхэттенского проекта — секретной разработки ядерного оружия.',
    poster_url: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 22100,
    genres: ['Биография', 'Драма', 'История'],
    country: 'США / Великобритания',
    director: 'Кристофер Нолан',
    cast: ['Киллиан Мёрфи', 'Эмили Блант', 'Мэтт Дэймон', 'Роберт Дауни мл.']
  },
  {
    id: 'c105-blade-runner-2049',
    tmdb_id: 335984,
    type: 'movie',
    title: 'Бегущий по лезвию 2049',
    original_title: 'Blade Runner 2049',
    release_year: 2017,
    age_rating: '18+',
    rating_imdb: 8.0,
    rating_tmdb: 7.9,
    runtime_minutes: 164,
    overview: 'В будущем мир населен людьми и репликантами, созданными для выполнения тяжелой работы. Офицер полиции Лос-Анджелеса Кей раскрывает давно погребенную тайну.',
    poster_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 15300,
    genres: ['Фантастика', 'Детектив', 'Драма'],
    country: 'США / Великобритания / Канада',
    director: 'Дени Вильнёв',
    cast: ['Райан Гослинг', 'Харрисон Форд', 'Ана де Армас']
  },
  {
    id: 'c106-arcane',
    tmdb_id: 94605,
    type: 'series',
    title: 'Аркейн',
    original_title: 'Arcane',
    release_year: 2021,
    age_rating: '16+',
    rating_imdb: 9.0,
    rating_tmdb: 8.7,
    runtime_minutes: 40,
    overview: 'Вай и Джинкс — две сестры, разделенные войной между богатым утопическим городом Пилтовером и его захудалым подземным соседом Зауном.',
    poster_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 31200,
    genres: ['Мультфильм', 'Фэнтези', 'Боевик'],
    country: 'США / Франция',
    director: 'Паскаль Шаррю',
    cast: ['Хейли Стайнфелд', 'Элла Пернелл']
  },
  {
    id: 'c107-dark-knight',
    tmdb_id: 155,
    type: 'movie',
    title: 'Темный рыцарь',
    original_title: 'The Dark Knight',
    release_year: 2008,
    age_rating: '16+',
    rating_imdb: 9.0,
    rating_tmdb: 8.5,
    runtime_minutes: 152,
    overview: 'Бэтмен поднимает ставки в войне с криминалом. С помощью лейтенанта Джима Гордона и прокурора Харви Дента он намеревается очистить улицы Готэма от преступности. Но вскоре они становятся добычей хаоса, развязанного гениальным Джокером.',
    poster_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 42000,
    genres: ['Боевик', 'Криминал', 'Драма'],
    director: 'Кристофер Нолан',
    cast: ['Кристиан Бэйл', 'Хит Леджер', 'Аарон Экхарт', 'Мэгги Джилленхол']
  },
  {
    id: 'c108-breaking-bad',
    tmdb_id: 1396,
    type: 'series',
    title: 'Во все тяжкие',
    original_title: 'Breaking Bad',
    release_year: 2008,
    age_rating: '18+',
    rating_imdb: 9.5,
    rating_tmdb: 8.9,
    runtime_minutes: 47,
    overview: 'Школьный учитель химии Уолтер Уайт узнает, что болен раком легких. Чтобы обеспечить финансовое будущее своей семьи, он объединяется со своим бывшим учеником Джесси Пинкманом для производства и продажи метамфетамина.',
    poster_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 51000,
    genres: ['Драма', 'Криминал', 'Триллер'],
    director: 'Винс Гиллиган',
    cast: ['Брайан Крэнстон', 'Аарон Пол', 'Анна Ганн', 'Дин Норрис']
  },
  {
    id: 'c109-matrix',
    tmdb_id: 603,
    type: 'movie',
    title: 'Матрица',
    original_title: 'The Matrix',
    release_year: 1999,
    age_rating: '16+',
    rating_imdb: 8.7,
    rating_tmdb: 8.2,
    runtime_minutes: 136,
    overview: 'Жизнь Томаса Андерсона разделена на две части: днем он обычный программист, а ночью — хакер Нео. Когда он встречает Морфеуса, перед ним открывается жуткая правда: привычный мир — лишь симуляция.',
    poster_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 38900,
    genres: ['Фантастика', 'Боевик'],
    director: 'Лана и Лилли Вачовски',
    cast: ['Киану Ривз', 'Лоренс Фишбёрн', 'Кэрри-Энн Мосс']
  },
  {
    id: 'c110-pulp-fiction',
    tmdb_id: 680,
    type: 'movie',
    title: 'Криминальное чтиво',
    original_title: 'Pulp Fiction',
    release_year: 1994,
    age_rating: '18+',
    rating_imdb: 8.9,
    rating_tmdb: 8.5,
    runtime_minutes: 154,
    overview: 'Двое гангстеров Винсент Вега и Джулс Виннфилд ведут философские беседы в перерывах между разборками и выполнением поручений своего босса Марселласа Уоллеса.',
    poster_url: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 34500,
    genres: ['Криминал', 'Драма', 'Комедия'],
    director: 'Квентин Тарантино',
    cast: ['Джон Траволта', 'Сэмюэл Л. Джексон', 'Ума Турман', 'Брюс Уиллис']
  },
  {
    id: 'c111-inception',
    tmdb_id: 27205,
    type: 'movie',
    title: 'Начало',
    original_title: 'Inception',
    release_year: 2010,
    age_rating: '12+',
    rating_imdb: 8.8,
    rating_tmdb: 8.3,
    runtime_minutes: 148,
    overview: 'Кобб — талантливый вор, лучший в опасном искусстве извлечения: он крадет ценные секреты из глубин подсознания во время сна, когда человеческий разум наиболее уязвим. Редкие способности Кобба сделали его ценным игроком в привычном к шпионажу мире.',
    poster_url: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 36700,
    genres: ['Фантастика', 'Боевик', 'Триллер'],
    director: 'Кристофер Нолан',
    cast: ['Леонардо ДиКаприо', 'Джозеф Гордон-Левитт', 'Эллен Пейдж', 'Том Харди']
  },
  {
    id: 'c112-dune',
    tmdb_id: 438631,
    type: 'movie',
    title: 'Дюна',
    original_title: 'Dune',
    release_year: 2021,
    age_rating: '12+',
    rating_imdb: 8.0,
    rating_tmdb: 7.9,
    runtime_minutes: 155,
    overview: 'Наследник знаменитого дома Атрейдесов Пол отправляется вместе с семьей на одну из самых опасных планет во Вселенной — Арракис. Здесь нет ничего, кроме песка, палящего солнца, гигантских чудовищ и основной ценности Вселенной — спайса.',
    poster_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 24500,
    genres: ['Фантастика', 'Приключения', 'Драма'],
    director: 'Дени Вильнёв',
    cast: ['Тимоти Шаламе', 'Ребекка Фергюсон', 'Оскар Айзек', 'Джош Бролин']
  },
  {
    id: 'c113-godfather',
    tmdb_id: 238,
    type: 'movie',
    title: 'Крёстный отец',
    original_title: 'The Godfather',
    release_year: 1972,
    age_rating: '16+',
    rating_imdb: 9.2,
    rating_tmdb: 8.7,
    runtime_minutes: 175,
    overview: 'Криминальная сага о сицилийской мафиозной семье Корлеоне, проживающей в Нью-Йорке. Романтизированная, но жестокая картина жизни семьи, где традиции, верность и кодекс чести стоят превыше закона.',
    poster_url: 'https://images.unsplash.com/photo-1533928298208-27ff66555d8d?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1600&auto=format&fit=crop&q=80',
    is_4k: false,
    is_published: true,
    play_count: 41200,
    genres: ['Криминал', 'Драма'],
    director: 'Фрэнсис Форд Коппола',
    cast: ['Марлон Брандо', 'Аль Пачино', 'Джеймс Каан', 'Диана Китон']
  },
  {
    id: 'c114-shawshank',
    tmdb_id: 278,
    type: 'movie',
    title: 'Побег из Шоушенка',
    original_title: 'The Shawshank Redemption',
    release_year: 1994,
    age_rating: '16+',
    rating_imdb: 9.3,
    rating_tmdb: 8.9,
    runtime_minutes: 142,
    overview: 'Успешный банкир Энди Дюфрейн обвинён в убийстве собственной жены и её любовника. Оказавшись в тюрьме Шоушенк, он сталкивается с жестокостью и беззаконием, но находит способ сохранить надежду и волю к свободе.',
    poster_url: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?w=1600&auto=format&fit=crop&q=80',
    is_4k: false,
    is_published: true,
    play_count: 48900,
    genres: ['Драма', 'Криминал'],
    director: 'Фрэнк Дарабонт',
    cast: ['Тим Роббинс', 'Морган Фримен', 'Боб Гантон', 'Уильям Сэдлер']
  },
  {
    id: 'c115-green-mile',
    tmdb_id: 497,
    type: 'movie',
    title: 'Зелёная миля',
    original_title: 'The Green Mile',
    release_year: 1999,
    age_rating: '16+',
    rating_imdb: 8.9,
    rating_tmdb: 8.5,
    runtime_minutes: 189,
    overview: 'Обвиненный в страшном преступлении Джон Коффи оказывается в блоке смертников тюрьмы «Холодная гора». Вскоре начальник блока Пол Эджкомб обнаруживает, что этот гигант обладает удивительным даром исцеления.',
    poster_url: 'https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1600&auto=format&fit=crop&q=80',
    is_4k: false,
    is_published: true,
    play_count: 44200,
    genres: ['Драма', 'Фэнтези', 'Криминал'],
    director: 'Фрэнк Дарабонт',
    cast: ['Том Хэнкс', 'Дэвид Морс', 'Майкл Кларк Дункан', 'Бонни Хант']
  },
  {
    id: 'c116-forrest-gump',
    tmdb_id: 13,
    type: 'movie',
    title: 'Форрест Гамп',
    original_title: 'Forrest Gump',
    release_year: 1994,
    age_rating: '16+',
    rating_imdb: 8.8,
    rating_tmdb: 8.5,
    runtime_minutes: 142,
    overview: 'Полуслабоумный Форрест Гамп с самого детства привык идти своей дорогой, повинуясь лишь доброму сердцу. Его невероятная судьба превращает его в известного спортсмена, героя войны и миллиардера.',
    poster_url: 'https://images.unsplash.com/photo-1478720143023-ac02ec61132f?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1600&auto=format&fit=crop&q=80',
    is_4k: false,
    is_published: true,
    play_count: 39500,
    genres: ['Драма', 'Комедия', 'Мелодрама'],
    director: 'Роберт Земекис',
    cast: ['Том Хэнкс', 'Робин Райт', 'Гэри Синиз', 'Салли Филд']
  },
  {
    id: 'c117-lotr-1',
    tmdb_id: 120,
    type: 'movie',
    title: 'Властелин колец: Братство кольца',
    original_title: 'The Lord of the Rings: The Fellowship of the Ring',
    release_year: 2001,
    age_rating: '12+',
    rating_imdb: 8.8,
    rating_tmdb: 8.4,
    runtime_minutes: 178,
    overview: 'Хоббит Фродо Бэггинс отправляется в опасный поход к Роковой Горе, чтобы уничтожить Кольцо Всевластья, грозящее поработить все народы Средиземья под властью Тёмного Властелина Саурона.',
    poster_url: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 42100,
    genres: ['Фэнтези', 'Приключения', 'Боевик'],
    director: 'Питер Джексон',
    cast: ['Элайджа Вуд', 'Иэн Маккеллен', 'Вигго Мортенсен', 'Орландо Блум']
  },
  {
    id: 'c118-lotr-2',
    tmdb_id: 121,
    type: 'movie',
    title: 'Властелин колец: Две крепости',
    original_title: 'The Lord of the Rings: The Two Towers',
    release_year: 2002,
    age_rating: '12+',
    rating_imdb: 8.8,
    rating_tmdb: 8.4,
    runtime_minutes: 179,
    overview: 'Братство кольца распалось, но цель осталась прежней. Фродо и Сэм продолжают свой путь под предводительством Голлума, в то время как Арагорн, Леголас и Гимли защищают королевство Рохан от армий Сарумана.',
    poster_url: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 39800,
    genres: ['Фэнтези', 'Приключения', 'Боевик'],
    director: 'Питер Джексон',
    cast: ['Элайджа Вуд', 'Иэн Маккеллен', 'Вигго Мортенсен', 'Орландо Блум']
  },
  {
    id: 'c119-lotr-3',
    tmdb_id: 122,
    type: 'movie',
    title: 'Властелин колец: Возвращение короля',
    original_title: 'The Lord of the Rings: The Return of the King',
    release_year: 2003,
    age_rating: '12+',
    rating_imdb: 9.0,
    rating_tmdb: 8.5,
    runtime_minutes: 201,
    overview: 'Последняя великая битва за Средиземье начинается. Саурон бросает все силы на Минас Тирит, оплот людей, в то время как Фродо и Сэм подбираются к самому жерлу Ородруина.',
    poster_url: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 45000,
    genres: ['Фэнтези', 'Приключения', 'Боевик'],
    director: 'Питер Джексон',
    cast: ['Элайджа Вуд', 'Иэн Маккеллен', 'Вигго Мортенсен', 'Орландо Блум']
  },
  {
    id: 'c120-avatar',
    tmdb_id: 19995,
    type: 'movie',
    title: 'Аватар',
    original_title: 'Avatar',
    release_year: 2009,
    age_rating: '12+',
    rating_imdb: 7.9,
    rating_tmdb: 7.5,
    runtime_minutes: 162,
    overview: 'Бывший морпех Джейк Салли, прикованный к инвалидному креслу, отправляется на прекрасную, но враждебную Пандору, где корпорации добывают ценный минерал, угрожая существованию племени Нави.',
    poster_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 31200,
    genres: ['Фантастика', 'Приключения', 'Боевик'],
    director: 'Джеймс Кэмерон',
    cast: ['Сэм Уортингтон', 'Зои Салдана', 'Сигурни Уивер', 'Стивен Лэнг']
  },
  {
    id: 'c121-avatar-2',
    tmdb_id: 76600,
    type: 'movie',
    title: 'Аватар: Путь воды',
    original_title: 'Avatar: The Way of Water',
    release_year: 2022,
    age_rating: '16+',
    rating_imdb: 7.6,
    rating_tmdb: 7.7,
    runtime_minutes: 192,
    overview: 'После событий первого фильма Джейк Салли живет счастливой жизнью на Пандоре со своей семьей. Когда возвращаются старые враги, Салли вынужден покинуть свой лесной дом и просить убежища у водного клана Меткаина.',
    poster_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 28900,
    genres: ['Фантастика', 'Приключения', 'Боевик'],
    director: 'Джеймс Кэмерон',
    cast: ['Сэм Уортингтон', 'Зои Салдана', 'Сигурни Уивер', 'Кейт Уинслет']
  },
  {
    id: 'c122-mad-max',
    tmdb_id: 76341,
    type: 'movie',
    title: 'Безумный Макс: Дорога ярости',
    original_title: 'Mad Max: Fury Road',
    release_year: 2015,
    age_rating: '16+',
    rating_imdb: 8.1,
    rating_tmdb: 7.6,
    runtime_minutes: 120,
    overview: 'В постапокалиптическом мире Макс Рокатански объединяется с бунтаркой Фуриосой, чтобы спасти пяти жён Несмертного Джо и пересечь бескрайнюю пустыню на боевой фуре.',
    poster_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 29500,
    genres: ['Боевик', 'Фантастика', 'Приключения'],
    director: 'Джордж Миллер',
    cast: ['Том Харди', 'Шарлиз Терон', 'Николас Холт', 'Хью Кияс-Бёрн']
  },
  {
    id: 'c123-gladiator',
    tmdb_id: 98,
    type: 'movie',
    title: 'Гладиатор',
    original_title: 'Gladiator',
    release_year: 2000,
    age_rating: '16+',
    rating_imdb: 8.5,
    rating_tmdb: 8.2,
    runtime_minutes: 155,
    overview: 'Великий римский полководец Максимус, лишенный всего завистливым наследником престола Коммодом, становится гладиатором на аренах Рима, чтобы отомстить за смерть своей семьи.',
    poster_url: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 32000,
    genres: ['Боевик', 'Драма', 'Приключения'],
    director: 'Ридли Скотт',
    cast: ['Рассел Кроу', 'Хоакин Феникс', 'Конни Нильсен', 'Оливер Рид']
  },
  {
    id: 'c124-game-of-thrones',
    tmdb_id: 1399,
    type: 'series',
    title: 'Игра престолов',
    original_title: 'Game of Thrones',
    release_year: 2011,
    age_rating: '18+',
    rating_imdb: 9.2,
    rating_tmdb: 8.4,
    runtime_minutes: 57,
    overview: 'Семь благородных семей сражаются за власть над мистическими землями Вестероса, в то время как древний враг возвращается спустя тысячи лет из-за Стены на севере.',
    poster_url: 'https://images.unsplash.com/photo-1599837565318-67429bde7162?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 58900,
    genres: ['Фэнтези', 'Драма', 'Приключения'],
    director: 'Дэвид Бениофф',
    cast: ['Кит Харингтон', 'Эмилия Кларк', 'Питер Динклэйдж', 'Лина Хиди']
  },
  {
    id: 'c125-titanic',
    tmdb_id: 597,
    type: 'movie',
    title: 'Титаник',
    original_title: 'Titanic',
    release_year: 1997,
    age_rating: '12+',
    rating_imdb: 7.9,
    rating_tmdb: 7.9,
    runtime_minutes: 194,
    overview: 'Молодые влюбленные Джек и Роза находят друг друга в первом и последнем рейсе роскошного лайнера «Титаник». Их судьбоносная любовь разворачивается на фоне величайшей катастрофы.',
    poster_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 41200,
    genres: ['Драма', 'Мелодрама'],
    director: 'Джеймс Кэмерон',
    cast: ['Леонардо ДиКаприо', 'Кейт Уинслет', 'Билли Зейн', 'Кэти Бейтс']
  },
  {
    id: 'c126-green-book',
    tmdb_id: 490132,
    type: 'movie',
    title: 'Зелёная книга',
    original_title: 'Green Book',
    release_year: 2018,
    age_rating: '16+',
    rating_imdb: 8.2,
    rating_tmdb: 8.3,
    runtime_minutes: 130,
    overview: 'Утонченный чернокожий пианист Дон Ширли нанимает вышибалу Тони Болтуна в качестве водителя и телохранителя для тура по расистскому Югу США. В этой поездке они пользуются специальным путеводителем.',
    poster_url: 'https://images.unsplash.com/photo-1494548162494-384bba4ab999?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1494548162494-384bba4ab999?w=1600&auto=format&fit=crop&q=80',
    is_4k: false,
    is_published: true,
    play_count: 24100,
    genres: ['Драма', 'Комедия', 'Биография'],
    director: 'Питер Фаррелли',
    cast: ['Вигго Мортенсен', 'Махершала Али', 'Линда Карделлини', 'Себастьян Манискалко']
  },
  {
    id: 'c127-joker',
    tmdb_id: 475557,
    type: 'movie',
    title: 'Джокер',
    original_title: 'Joker',
    release_year: 2019,
    age_rating: '18+',
    rating_imdb: 8.4,
    rating_tmdb: 8.2,
    runtime_minutes: 122,
    overview: 'Готэм, начало 1980-х годов. Комик Артур Флек живет с больной матерью, которая с детства учит его «улыбаться и делать хорошую мину». Но сталкиваясь с человеческой жестокостью, Артур превращается в Джокера.',
    poster_url: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 38900,
    genres: ['Драма', 'Криминал', 'Триллер'],
    director: 'Тодд Филлипс',
    cast: ['Хоакин Феникс', 'Роберт Де Ниро', 'Зази Битц', 'Фрэнсис Конрой']
  },
  {
    id: 'c128-attack-on-titan',
    tmdb_id: 1429,
    type: 'series',
    title: 'Атака титанов',
    original_title: 'Attack on Titan',
    release_year: 2013,
    age_rating: '18+',
    rating_imdb: 9.1,
    rating_tmdb: 8.9,
    runtime_minutes: 24,
    overview: 'Уже сто лет человечество живёт в мире, окружённом высокими стенами, защищающими от гигантских людоедов — Титанов. Но в один день внешняя стена рушится, и юный Эрен Йегер клянётся уничтожить каждого Титана.',
    poster_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1600&auto=format&fit=crop&q=80',
    is_4k: true,
    is_published: true,
    play_count: 47600,
    genres: ['Аниме', 'Боевик', 'Фэнтези', 'Драма'],
    director: 'Тэцуро Араки',
    cast: ['Юки Кадзи', 'Юи Исикава', 'Марина Иноуэ']
  },
  {
    id: 'c129-spirited-away',
    tmdb_id: 129,
    type: 'movie',
    title: 'Унесённые призраками',
    original_title: 'Spirited Away',
    release_year: 2001,
    age_rating: '12+',
    rating_imdb: 8.6,
    rating_tmdb: 8.5,
    runtime_minutes: 125,
    overview: 'Маленькая Тихиро вместе с родителями переезжает в новый дом, но случайно оказывается в таинственном мире богов, духов и призраков, где заправляет злая колдунья Юбаба. Чтобы спасти заколдованных родителей, девочке приходится работать в купальнях для духов.',
    poster_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=80',
    backdrop_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&auto=format&fit=crop&q=80',
    is_4k: false,
    is_published: true,
    play_count: 32100,
    genres: ['Аниме', 'Мультфильм', 'Фэнтези', 'Приключения'],
    director: 'Хаяо Миядзаки',
    cast: ['Руми Хираги', 'Мию Ирино', 'Мари Нацуки']
  }
];

export const initialSeasons: Season[] = [
  {
    id: 's-cp-1',
    content_id: 'c103-cyberpunk-edgerunners',
    season_number: 1,
    title: 'Сезон 1',
    overview: 'Становление Дэвида Мартинеса в Найт-Сити.',
    poster_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 's-arc-1',
    content_id: 'c106-arcane',
    season_number: 1,
    title: 'Сезон 1',
    overview: 'Зарождение конфликта между Пилтовером и Зауном.',
    poster_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 's-got-1',
    content_id: 'c124-game-of-thrones',
    season_number: 1,
    title: 'Сезон 1',
    overview: 'Лорд Эддард Старк вызван своим королем Робертом Баратеоном в Королевскую Гавань, чтобы стать Десницей короля, в то время как древнее зло пробуждается за великой Стеной.',
    poster_url: 'https://images.unsplash.com/photo-1599837565318-67429bde7162?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 's-aot-1',
    content_id: 'c128-attack-on-titan',
    season_number: 1,
    title: 'Сезон 1',
    overview: 'Знакомство с миром стен и первыми атаками гигантских титанов.',
    poster_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80'
  }
];

export const initialEpisodes: Episode[] = [
  {
    id: 'e-cp-101',
    season_id: 's-cp-1',
    episode_number: 1,
    title: 'Серия 1: Человек из стали',
    overview: 'Дэвид пытается справиться с трагедией и находит странный имплант.',
    runtime_minutes: 25,
    still_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
    air_date: '13.09.2022'
  },
  {
    id: 'e-cp-102',
    season_id: 's-cp-1',
    episode_number: 2,
    title: 'Серия 2: Люси',
    overview: 'Дэвид знакомится с Люси в метро Найт-Сити.',
    runtime_minutes: 24,
    still_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    air_date: '13.09.2022'
  },
  {
    id: 'e-arc-101',
    season_id: 's-arc-1',
    episode_number: 1,
    title: 'Серия 1: Нам нужен только ты',
    overview: 'Сироты из Зауна совершают дерзкую кражу в Верхнем городе.',
    runtime_minutes: 42,
    still_url: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80',
    air_date: '06.11.2021'
  },
  {
    id: 'e-got-101',
    season_id: 's-got-1',
    episode_number: 1,
    title: 'Серия 1: Зима близко',
    overview: 'Король Роберт Баратеон приезжает в Винтерфелл, чтобы предложить Эддарду Старку пост Десницы. За Стеной разведчики Ночного Дозора сталкиваются с Белыми Ходоками.',
    runtime_minutes: 62,
    still_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    air_date: '17.04.2011'
  },
  {
    id: 'e-got-102',
    season_id: 's-got-1',
    episode_number: 2,
    title: 'Серия 2: Королевский тракт',
    overview: 'Старки отправляются на юг, а Джон Сноу едет на север, чтобы присягнуть Ночному Дозору. Конфликт между Джоффри и Арьей приводит к трагическим последствиям.',
    runtime_minutes: 56,
    still_url: 'https://images.unsplash.com/photo-1599837565318-67429bde7162?w=800&auto=format&fit=crop&q=80',
    air_date: '24.04.2011'
  },
  {
    id: 'e-aot-101',
    season_id: 's-aot-1',
    episode_number: 1,
    title: 'Серия 1: К тебе через 2000 лет',
    overview: 'Внезапное появление Колоссального Титана разрушает стену Мария, разделяя привычную жизнь жителей Шиганши на "до" и "после".',
    runtime_minutes: 24,
    still_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
    air_date: '07.04.2013'
  }
];

export const initialCollections: Collection[] = [
  {
    id: 'col-4k-hdr',
    name: '4K Ultra HDR Шедевры',
    slug: '4k-hdr-masterpieces',
    description: 'Контент с максимальной детализацией и расширенным динамическим диапазоном.',
    poster_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    sort_order: 1
  },
  {
    id: 'col-sci-fi',
    name: 'Научная Фантастика и Киберпанк',
    slug: 'sci-fi-cyberpunk',
    description: 'Лучшие миры будущего, ИИ, освоение космоса и кибернетика.',
    poster_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    is_active: true,
    sort_order: 2
  }
];

export const initialNodes: NodeHealthStatus[] = [
  {
    nodeId: 'node-local-01',
    hostname: '127.0.0.1:8090',
    region: 'Local / Edge Direct',
    isOnline: false, // Initially false until pinged or telemetry ingested
    cpuUsagePercent: 0,
    ramUsagePercent: 0,
    bandwidthMbps: 0,
    activeStreams: 0,
    maxCapacity: 50,
    loadFactor: 0
  }
];

// In-Memory Database Controller State
export class DatabaseStore {
  users: User[] = [
    {
      id: 'usr-admin-01',
      email: 'admin@smarttv.com',
      username: 'smarttv_admin',
      role: 'admin',
      is_blocked: false,
      created_at: new Date().toISOString()
    },
    {
      id: 'usr-demo-01',
      email: 'demo@smarttv.com',
      username: 'tv_viewer',
      role: 'user',
      is_blocked: false,
      created_at: new Date().toISOString()
    }
  ];

  devices: Device[] = [];
  transactions: any[] = [];

  content: ContentItem[] = [...initialContent];
  seasons: Season[] = [...initialSeasons];
  episodes: Episode[] = [...initialEpisodes];
  collections: Collection[] = [...initialCollections];
  favorites: Map<string, Set<string>> = new Map();
  watchlist: Map<string, Set<string>> = new Map();
  history: WatchHistoryItem[] = [];
  nodes: NodeHealthStatus[] = [...initialNodes];
  sessions: PlaybackSession[] = [];
}

export const dbStore = new DatabaseStore();
